### PR TITLE
Fix cancel order notification parsing

### LINKED ISSUE #272: Not able to parse Cancel Order Response from Openfinex
Response_handle is throwing error while parsing response:-
```
[2021-08-31T07:03:24Z ERROR substratee_worker_enclave::openfinex::openfinex_api_impl] Sending order to openfinex: [1,0,"admin_cancel_order",["btcusd",["86a36f48-0a29-11ec-9287-0242ac170002"]]]
[2021-08-31T07:03:24Z ERROR substratee_worker_enclave::openfinex::response_lexer] Response from openfinex: "[2,0,\"admin_cancel_order\",[]]"
[2021-08-31T07:03:24Z ERROR substratee_worker_enclave::openfinex::response_handler] Failed to map response to objects: ResponseParsingError("Unknown or unsupported request type (CancelOrder), cannot map to response")
[2021-08-31T07:03:24Z ERROR substratee_worker_enclave::openfinex::response_lexer] Response from openfinex: "[5,\"oc\",[\"ALICE\",\"5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY\",\"btcusd\",1,\"86a36f48-0a29-11ec-9287-0242ac170002\",\"sell\",\"c\",\"l\",\"0.001\",\"0\",\"0.005\",\"0.005\",\"0\",0,1630393401]]"
```
And as mentioned in Issue #149. Which message we should treat as Success response?

### PR DESCRIPTION
**Pull request by haerdib**

### CODE REVIEW

**Comment by zktony** [comment]
@haerdib I am getting this :-
```
[2021-09-03T05:56:06Z ERROR substratee_worker_enclave::openfinex::response_lexer] Response from openfinex: "[5,\"oc\",[\"ALICE\",\"5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY\",\"btcusd\",1,\"9f0aa5a4-0c7b-11ec-93f7-0242ac120008\",\"sell\",\"c\",\"l\",\"0.001\",\"0\",\"0.005\",\"0.005\",\"0\",0,1630648563]]"
[2021-09-03T05:56:06Z ERROR substratee_worker_enclave::openfinex::response_handler] Failed to map response to objects: ResponseParsingError("Could not find a market object in cache for id 'btcusd'")
Enclave wants to send 2 extrinsics
```
When i printed Market Cache :-
`[2021-09-03T06:17:03Z ERROR substratee_worker_enclave::openfinex::string_serialization] market_cache: MarketCache { markets: {}, request_id: 1 }`

**Comment by zktony** [comment]
Maybe this bug https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/277 is connected for above logs.

**Comment by haerdib** [comment]
You could be right: see this issue : https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/105 (and the assosciated PR: https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/132) - we have based our markets (and the request id) on the `get_market ` function of Openfinex.

**Comment by zktony** [comment]
yes @haerdib .. I also think so

**Comment by zktony** [comment]
Changes merged into #267

**Pull request closed without merging**
