### PR TITLE
Added benchmark feature

### LINKED ISSUE #222: Add Feature Benchmark that allows to build the worker such that it will not verify the nonce
**Problem**
The benchmarking code sends transactions in Parallel. So the sequence of requests cannot be controlled, and hence it can't be benchmarked as Worker code verifies nonce as well and expect it to follow the series.

### PR DESCRIPTION
**Pull request by zktony**
Added new updated authorize_trusted_call function. Which will be only called when 'benchmarking' feature is used.
 Will close #222

### CODE REVIEW

**Comment by zktony** [comment]
Hey @haerdib, I belive we also have to update Make file to include Benchmarking Feature. Let me know what all I have to update.

**Review by haerdib — CHANGES_REQUESTED** [review]
LGTM. For the makefile I'd add a `make benchmark` command:

```make
.PHONY: benchmark
benchmark:
	@echo "Compiling in benchmark mode"
	..
```

where it should be exactly the same as https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/Makefile#L146
but instead of `cargo build $(Client_Rust_Flags)`  `cargo build $(Client_Rust_Flags) --features benchmark` 
here:
-https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/Makefile#L170
-https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/Makefile#L179
and the enclave, also add a new `make benchmark` cmd:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/Makefile
with an adapted cargo build cmd:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/Makefile#L50

when calling the enclave make, ensure make benchmark is called, not make all

(for example you could add an enclave benchmark call:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/Makefile#L201-L205) and call it here: 
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/Makefile#L188

**Review by simonsso — COMMENTED** [review]
Makefiles are black magic, it is well known in the industry, is there an easy way to solve these warnings?

```
simson@tama:~/polkadex/polkadexTEE-worker$ make benchmark
Makefile:208: warning: overriding recipe for target 'enclave/Enclave_t.c'
Makefile:154: warning: ignoring old recipe for target 'enclave/Enclave_t.c'
Makefile:208: warning: overriding recipe for target 'enclave/Enclave_t.h'
Makefile:154: warning: ignoring old recipe for target 'enclave/Enclave_t.h'
Makefile:208: warning: overriding recipe for target 'worker/Enclave_u.c'
Makefile:154: warning: ignoring old recipe for target 'worker/Enclave_u.c'
Makefile:208: warning: overriding recipe for target 'worker/Enclave_u.h'
Makefile:154: warning: ignoring old recipe for target 'worker/Enclave_u.h'
Makefile:214: warning: overriding recipe for target 'worker/Enclave_u.o'
Makefile:160: warning: ignoring old recipe for target 'worker/Enclave_u.o'
Makefile:218: warning: overriding recipe for target 'worker/libEnclave_u.a'
Makefile:164: warning: ignoring old recipe for target 'worker/libEnclave_u.a'
Makefile:222: warning: overriding recipe for target 'bin/app'
Makefile:168: warning: ignoring old recipe for target 'bin/app'
Makefile:231: warning: overriding recipe for target 'bin/substratee-client'
Makefile:177: warning: ignoring old recipe for target 'bin/substratee-client'
Makefile:239: warning: overriding recipe for target 'enclave/Enclave_t.o'
Makefile:185: warning: ignoring old recipe for target 'enclave/Enclave_t.o'
Makefile:243: warning: overriding recipe for target 'enclave/enclave.so'
Makefile:189: warning: ignoring old recipe for target 'enclave/enclave.so'
Makefile:248: warning: overriding recipe for target 'bin/enclave.signed.so'
Makefile:194: warning: ignoring old recipe for target 'bin/enclave.signed.so'
Makefile:266: warning: overriding recipe for target 'enclave'
Makefile:257: warning: ignoring old recipe for target 'enclave'
Makefile:271: warning: overriding recipe for target '.git/hooks/pre-commit'
Makefile:262: warning: ignoring old recipe for target '.git/hooks/pre-commit'
```

**Comment by zktony** [comment]
> Makefiles are black magic, it is well known in the industry, is there an easy way to solve these warnings?
> 
> ```
> simson@tama:~/polkadex/polkadexTEE-worker$ make benchmark
> Makefile:208: warning: overriding recipe for target 'enclave/Enclave_t.c'
> Makefile:154: warning: ignoring old recipe for target 'enclave/Enclave_t.c'
> Makefile:208: warning: overriding recipe for target 'enclave/Enclave_t.h'
> Makefile:154: warning: ignoring old recipe for target 'enclave/Enclave_t.h'
> Makefile:208: warning: overriding recipe for target 'worker/Enclave_u.c'
> Makefile:154: warning: ignoring old recipe for target 'worker/Enclave_u.c'
> Makefile:208: warning: overriding recipe for target 'worker/Enclave_u.h'
> Makefile:154: warning: ignoring old recipe for target 'worker/Enclave_u.h'
> Makefile:214: warning: overriding recipe for target 'worker/Enclave_u.o'
> Makefile:160: warning: ignoring old recipe for target 'worker/Enclave_u.o'
> Makefile:218: warning: overriding recipe for target 'worker/libEnclave_u.a'
> Makefile:164: warning: ignoring old recipe for target 'worker/libEnclave_u.a'
> Makefile:222: warning: overriding recipe for target 'bin/app'
> Makefile:168: warning: ignoring old recipe for target 'bin/app'
> Makefile:231: warning: overriding recipe for target 'bin/substratee-client'
> Makefile:177: warning: ignoring old recipe for target 'bin/substratee-client'
> Makefile:239: warning: overriding recipe for target 'enclave/Enclave_t.o'
> Makefile:185: warning: ignoring old recipe for target 'enclave/Enclave_t.o'
> Makefile:243: warning: overriding recipe for target 'enclave/enclave.so'
> Makefile:189: warning: ignoring old recipe for target 'enclave/enclave.so'
> Makefile:248: warning: overriding recipe for target 'bin/enclave.signed.so'
> Makefile:194: warning: ignoring old recipe for target 'bin/enclave.signed.so'
> Makefile:266: warning: overriding recipe for target 'enclave'
> Makefile:257: warning: ignoring old recipe for target 'enclave'
> Makefile:271: warning: overriding recipe for target '.git/hooks/pre-commit'
> Makefile:262: warning: ignoring old recipe for target '.git/hooks/pre-commit'
> ```

Haha .. Yes @simonsso. Hey @haerdib could you please help me with these warnings. It is first time, I am working with it.😅

**Review by haerdib — APPROVED** [review]
LGTM

**Pull request merged**
