### PR TITLE
Update build.yml

### LINKED ISSUE #179: Remove clippy warnings & check clippy warnings with PR
There are new clippy warnings which should be removed. After solving this issue, new PRs should be checked if they bring in new clippy warnings. If they do, CI should throw warnings / errors.

### PR DESCRIPTION
**Pull request by zktony**
Updated Clippy command for Client, Worker and Enclave. Partially solves #179

### CODE REVIEW

**Comment by zktony** [comment]
I think its working

**Comment by Gauthamastro** [comment]
@zktony The CI is failing

**Comment by zktony** [comment]
yes @Gauthamastro it should fail as there are some warnings in the code.

**Comment by zktony** [comment]
I will remove them in sometime.

**Comment by Gauthamastro** [comment]
> I will remove them in someti

> I will remove them in sometime.

The CI issues will be fixed as soon as #179 is merged

**Comment by haerdib** [comment]
I've added a cargo fmt check as well as separated the clippy job from the build job. What do you think about these changes @zktony  and @Gauthamastro ?

**Comment by zktony** [comment]
LGTM @haerdib

**Review by haerdib — APPROVED** [review]
LGTM

**Pull request merged**
